### ISSUE TITLE
Create footer according to Figma design

### ISSUE THREAD

**Issue by bambooch** [zeforgezenica/smetoviba#10]
![image](https://github.com/user-attachments/assets/5212eacc-2717-4f43-a8e2-16be17da2abd)

The asset for the background is available to export from Figma, just ping me here to export it whoever takes this first.

**Comment by barichh** [comment]
Deder ovo da sredim hahaha

**Comment by bambooch** [comment]
> Deder ovo da sredim hahaha

evo assign sam te, saljem na Discord export ovog dole
